### ISSUE TITLE
example not working

### ISSUE THREAD

**Issue by hossmaa** [opener-project/language-identifier#3]
Hello!

I've followed the getting started instructions for a local installation from here: http://www.opener-project.eu/getting-started/how-to/local-installation.html
Everything worked fine until I tried to execute the first example: 
```echo "This is absolutelty great" | language-identifier```
When I do this, I get a load error for a .jar:
```[...]/opener-language-identifier-4.2.2/lib/opener/language_identifier.rb:5:in `require_relative': cannot load such file -- [...]/opener-language-identifier-4.2.2/core/target/LanguageDetection-1.0.0.jar (LoadError)```
The .jar file is present in the specified path, so I really don't understand what the problem is...

Can you help me, please?
Thanks!

**Comment by YorickPeterse** [comment]
Make sure you're running `language-identifier` using JRuby. We've seen this error before and I recall it was caused by the command being run using the default Ruby instead of JRuby. You can try the following:

    gem pristine opener-language-identifier --env-shebang

If that spits out some error:

    gem install opener-language-identifier --env-shebang

If this solves the problem you can make this permanent by opening `~/.gemrc` and making sure this file looks like the following:

    ---
    install: --env-shebang
    update:  --env-shebang

**Comment by hossmaa** [comment]
Hi Yorick

That didn't work unfortunately. Here the output of ```gem env```
```
RubyGems Environment:
  - RUBYGEMS VERSION: 2.1.11
  - RUBY VERSION: 2.0.0 (2013-11-22 patchlevel 353) [x86_64-linux]
  - INSTALLATION DIRECTORY: /home/andreea/.gem/ruby
  - RUBY EXECUTABLE: /usr/bin/ruby
  - EXECUTABLE DIRECTORY: /home/andreea/bin
  - SPEC CACHE DIRECTORY: /home/andreea/.gem/specs
  - RUBYGEMS PLATFORMS:
    - ruby
    - x86_64-linux
  - GEM PATHS:
     - /home/andreea/.gem/ruby
     - /usr/share/gems
     - /usr/local/share/gems
  - GEM CONFIGURATION:
     - :update_sources => true
     - :verbose => true
     - :backtrace => false
     - :bulk_threshold => 1000
  - REMOTE SOURCES:
     - https://rubygems.org/
  - SHELL PATH:
     - /home/andreea/.virtualenvs/opener/bin
     - /usr/lib64/ccache
     - /usr/local/bin
     - /usr/bin
     - /bin
     - /usr/games
     - /usr/local/sbin
     - /usr/sbin
     - /home/andreea/bin
     - /usr/local/MATLAB/R2010b/bin
     - /usr/local/mobius/Mobius-2.3/bin
```

**Comment by YorickPeterse** [comment]
Ah, it appears that your Ruby environment is set to regular Ruby instead of JRuby. Does this work?:

    jruby -S gem install opener-language-identifier
    echo 'Some input text here' | jruby -S language-identifier

**Comment by hossmaa** [comment]
I think it's a problem with my version of jruby (1.9). Are you using this? Or an older one?
```jruby -S gem install opener-language-identifier
ERROR:  Error installing opener-language-identifier:
        invalid gem: package is corrupt, exception while verifying: (<unknown>): 'reader' unacceptable character '' (0x8B) special characters are not allowed
in "'reader'", position 4311 at line 0 column 0 (Psych::SyntaxError) in /home/andreea/.gem/jruby/1.9/cache/nokogiri-1.6.6.2-java.gem
```

**Comment by YorickPeterse** [comment]
How did you install JRuby, did you use your system's package manager or installed it by hand?

Alternatively you could try using https://github.com/postmodern/chruby and https://github.com/postmodern/ruby-install. This process requires a bit more manual work but will give you a Ruby setup that is fully isolated from the system much like virtualenv. Basically install both chruby and ruby-install then run the following:

    ruby-install jruby
    chruby jruby

Running `ruby --version` should now output something like:

    jruby 1.7.18 (1.9.3p551) 2014-12-22 625381c on OpenJDK 64-Bit Server VM 1.7.0_79-b14 +jit [linux-amd64]

You can then install the tools using:

    gem install opener-language-identifier
    echo 'hello world' | language-identifier

If this works I'll update the installation guides to include this to save others from having to go through the same troubles.

**Comment by hossmaa** [comment]
I installed JRuby via the system's package manager.
Now I also installed nokogiri (the problematic package from earlier) directly through the package manager. Then this worked:
```jruby -S gem install opener-language-identifier```

And also the language identification test finally worked.

Thanks so much for the fast support!

**Comment by YorickPeterse** [comment]
Ah, great to hear that solved the problem!

**Comment by gnespatel** [comment]
Hi @YorickPeterse I am getting the following error can you help me?  
gem install opener-language-identifier
speed 38400 baud; line = 0;
-brkint -imaxbel iutf8
ERROR:  Loading command: install (LoadError)
	library `zlib' could not be loaded: java.lang.NoClassDefFoundError: Could not initialize class org.jruby.ext.zlib.RubyZlib
ERROR:  While executing gem ... (NoMethodError)
    undefined method `invoke_with_build_args' for nil:NilClass
